### ISSUE TITLE
integration in my game

### ISSUE THREAD

**Issue by pyweeker** [JoJoJet/bevy-mouse-tracking#6]
Hello, could you fork my project here and show how it does work with your library, thats exactly the tool i was looking for !
The previous alternative i found was
https://github.com/anshorei/bevy_rei/tree/HEAD/bevy_interact_2d
but only works on bevy0.5

i need to get datas about hovered entities (maybe with a tooltip ?) but above all select single entity by clicking on it,
and make squad of entities while click and drag upon them.

Hope you can do something with it ...

https://github.com/pyweeker/Bevy_and_Egui

**Comment by joseph-gio** [comment]
I'm not really looking to just do the implementation work for your game, but I'm willing to answer any questions you have or share ideas. If you wanna add me on discord I can send you my handle.

**Comment by pyweeker** [comment]
Hello , i rarely go on discord, but could you provide on your repo an
example on hovering, selecting sprite and geting his entity owner ?
something basic and universal ?
